#!/usr/bin/env /bin/bash

set -f

function process_lines()
{
    local line
    local index
    local codec_long_name
    local codec_type
    local language
    
    while read line
    do
        if [ $category = STREAM ]
        then
            [[ $line =~ \[/(.+)\] ]] && echo $index: $codec_type \($language\) $codec_long_name && break
            if [[ $line =~ (.+)=(.+) ]]
            then
                key=${BASH_REMATCH[1]}
                value=${BASH_REMATCH[2]}
                
                case $key in
                    index)
                        index=$value
                    ;;
                    codec_long_name)
                        codec_long_name="$value"
                    ;;
                    codec_type)
                        codec_type=$value
                    ;;
                    TAG:language)
                        language=$value
                    ;;
                esac
            fi
        elif [ $category = FORMAT ]
        then
            [[ $line =~ \[/(.+)\] ]] && break
            echo $line
        fi
    done
    
}

function read_media_info()
{
    local line
    while read line
    do
        if [[ $line =~ \[([^/]+)\] ]]
        then
            local category=${BASH_REMATCH[1]}
            process_lines $category
        fi
    done
}

function main()
{
    for a in "$@"
    do
       echo $a
       echo    
       ffprobe -hide_banner -show_streams \
       -show_entries format_tags:stream=index,codec_long_name,codec_type:stream_tags=language:disposition= \
       "${a}" 2>/dev/null | read_media_info
       echo
    done
    return 0
}

(( $# >= 1 )) && main "$@" || echo "$(basename "$0") [FILES]"
